name: oh_nego_ttk
description: Tropa do NG
publish_to: ""

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/header_reference.jpg